### ISSUE TITLE
Any possibilities to disable some search engine 

### ISSUE THREAD

**Issue by simo97** [Sanix-Darker/falla#2]
i've pulled this but actually Docker doesn't work on my machine right now, and it seem like some search engine does not require it to work. Like a plugin system, allowing to disable the one requiring Docker to work.

**Comment by Sanix-Darker** [comment]
Falla has 3 mode of fetching results on search-engine :
- Using a simple requests
- Using Selenium
- Using the docker-splash-scrap

Some search-engine scraper's class have been made with the mode `splash-scrap` ,this mode send the url to the docker container running on port 8050, like i said in the README, it's not required to install it, but for some search-engine, you need to have it !
