### ISSUE TITLE
Selemium problem

### ISSUE THREAD

**Issue by simo97** [Sanix-Darker/falla#3]
Having this issue when running the command from the example.
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
![Capture d’écran 2020-04-29 à 09 02 50](https://user-images.githubusercontent.com/14660547/80573868-b7658580-89f8-11ea-95b4-b9561bff42f3.png)

I am on MacBook Pro (Mac OS Mojave)

**Comment by Sanix-Darker** [comment]
Have you follow the installation of geckodriver for MacOS like it was specify on the README ?
when you follow this link : https://github.com/mozilla/geckodriver/releases , you install geckodriver "FOR MAC-OS" !

Let me know if you're still having issues !

PS: FALLA have not been tested on Mac OS.

**Comment by simo97** [comment]
there is nothing related to specific trick when installing it on MacOS. btw i will try this later

**Comment by Sanix-Darker** [comment]
Any updates here @simo97 ?

**Comment by simo97** [comment]
Nope... sorry am sick right now

**Comment by Sanix-Darker** [comment]
Closing this issue due to any activity !

**Comment by simo97** [comment]
will update later
